### ISSUE TITLE
Authentication Timer too short

### ISSUE THREAD

**Issue by Republicof1** [orppst/pst-gui#226] opened 2024-08-07 12:49 UTC
Increase timer to allow users to be idle for a more permissive amount of time

**Comment by pahjbo** [comment] 2024-08-07 14:14
is this not a duplicate of #197 ?

**Comment by Republicof1** [comment] 2024-08-19 13:38
yep, you're right - just testing the branch now. It tick off #197 as the same thing

**Closed** 2024-08-21 14:17 UTC
